foreground #faf4ed
background #15a6d7

background_opacity .6

#: black
color0 #191724
color8 #1f1d2e

#: red
color1 #eb6f92
color9 #eb6f92

#: green
color2 #9aa98f
color10 #737e6b

#: yellow
color3 #f6c177
color11 #f6c177

#: blue
color4 #3e8fb0
color12 #31748f

#: mangenta
color5 #c4a7e7
color14 #c4a7e7

#: cyan
color6 #88c0d0
color14 #8fbcbb

#: white
color7 #e5e9f0
color14 #eceff4
